name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        target: wasm32-unknown-unknown
        toolchain: stable

    - uses: Swatinem/rust-cache@v2

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - run: corepack enable

    - uses: extractions/setup-crate@v1
      with:
        owner: sigoden
        name: argc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: npm install
    - run: argc test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}