name: npm
on: 
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: npm publish
        env:
          NPM_AUTH_TOKEN : ${{ secrets.NPM_TOKEN }}